### ISSUE TITLE
Add gdal2 support

### ISSUE THREAD

**Issue by joto** [osmcode/libosmium#107]
Make libosmium work with gdal/ogr 1 and 2.

This is currently waiting for gdal 2 support in Debian.

**Comment by springmeyer** [comment]
Can you just install GDAL 2.0 from source on your machine and add the necessary ifdefs to fix the compile? Let's not wait for debian support to ensure builds work against both gdal 1.11.x and 2.x.

**Comment by BergWerkGIS** [comment]
@joto ping me, when `gdal@2.0` support has landed, that I'll update the Windows binary deps package.
Current one is with `gdal@1.11.2`.

**Comment by sebastic** [comment]
joto wrote:
> This is currently waiting for gdal 2 support in Debian.

You can build GDAL 2.0 from the [experimental-2.0 branch](http://anonscm.debian.org/cgit/pkg-grass/gdal.git/log/?h=experimental-2.0) as I wrote in the [GDAL 2.0.0](https://lists.debian.org/debian-gis/2015/06/msg00070.html) thread on the `debian-gis` list:
> The Release Team also thought [1] we should transition to GDAL 1.11.2
> first because that transition can be started now, we can then use
> experimental to resolve any GDAL 2.0.0 issues in reverse dependencies.
> 
> The GDAL 2.0.0 packaging will only be available in git for the time
> being for interested parties to build themselves.
> 
> [1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=756867#117

Because we just started the transition to GDAL 1.11.2 in Debian, we need to complete that before starting a new transition to GDAL 1.11.3 or 2.0.1 ([due soon](https://lists.osgeo.org/pipermail/gdal-dev/2015-August/042367.html)).

Regarding those plans I wrote the following in the [GDAL/OGR 1.11.2](https://lists.debian.org/debian-gis/2015/08/msg00121.html) thread:
> GDAL upstream is planning to release 1.11.3 and 2.0.1 soon. Depending on
> how easy the GDAL 2.0 issues in the reverse dependencies can be fixed,
> I'll upload 1.11.3 to experimental shortly after its release or 2.0.1
> instead.
> [...]
> Depending on the results of my rebuilds with GDAL 2.0, we may stick to
> GDAL 1.11.x in Debian a bit longer. Which ever version we take it will
> require a new transition.

**Comment by joto** [comment]
I found a small wrapper "lib" I wrote before that works with GDAL 1 and 2. It was only used in https://github.com/osmcode/osmium-contrib/tree/master/mapolution, but I extracted it into its own repository [joto/gdalcpp](https://github.com/joto/gdalcpp) and used it now here and in [osm-gis-export](https://github.com/osmcode/osm-gis-export), too.

@springmeyer, @BergWerkGIS, @tomhughes: please test if you want to.

**Comment by tomhughes** [comment]
Yes that seems to work on both my platforms.

**Comment by joto** [comment]
@BergWerkGIS: Okay, seems GDAL 2 support works now. You can change the Windows build over if you want to, but GDAL 1 is also still supported, so there is no hurry.

**Comment by BergWerkGIS** [comment]
@joto I updated the binary deps pacakge to `gdal@2.0.0`.
AppVeyor is happy: https://ci.appveyor.com/project/Mapbox/libosmium/build/1.0.265

I think it's good to close from a Windows point of view.
