### ISSUE TITLE
Windows line endings

### ISSUE THREAD

**Issue by joto** [osmcode/libosmium#109]
Osmium currently opens files on Windows with `open()` using `O_BINARY`. I am not sure this is right. But even after spending some quality time with Google I can't figure out what the right behaviour is on Windows concerning line endings. I know that Windows uses CRLF line endings in text files as opposed to Unix which uses just LF. But I don't know what that means in practice. Ideally the files Osmium creates would be in the format Windows users are used to. What does an OSM file downloaded from planet.osm.org or from the OSM API look like?

We have three different cases:
- Binary file formats like PBF (obviously we don't want any line ending conversions in this case, so need to open file with `O_BINARY`)
- Text formats like XML and OPL (we might want CRLF on Windows in these cases, so either open with `O_BINARY` or write CRLF ourselves?)
- Packed text formats (.osm.gz, .osm.bz2) - When writing a file like this in Osmium the result should be the same as when I write it as text and call `gzip` binary on it afterwards. What does gzip do?

Also what about performance? Adding all those CR before each LF with `O_BINARY` means there is another copy somewhere in the Windows runtime. Is this a problem?

@BergWerkGIS: Can you shed some light on this?

**Comment by DerDakon** [comment]
Gzip does not alter the contents of the stream, nor does it care about line endings or anything in the stream. So if you write texts with CRLF before piping through gzip those will be preserved.

**Comment by BergWerkGIS** [comment]
My suggestion: leave as is.

* I see libosmium's audience to be developers. Those are used to handling Unix line endings, even on Windows.
* Almost all text/xml editors (except Notepad, that comes with Windows) handle Windows/Unix line endings transparently (Sublime Text, Notepad++, ...)

> Also what about performance?

Files would be a bit bigger, as the CRs needs some additional space to be saved.
I suppose, that would only make a difference with really big files.
And, any tests that check for file size would have to be adjusted.

**Comment by joto** [comment]
The audience of libosmium is developers, that's true. But this is about files generated by libosmium which will affect every application using libosmium including end-user-facing ones.

I think the most important issue here is consistency: If I download a file from planet.osm.org or thru the API, how do they look? What does Osmosis do? If I take any of those OSM files and read it with Osmium and write it out again, will it have the same line endings or different ones?

**Comment by BergWerkGIS** [comment]
Here's the Catch 22 problem:

* `osm`/`opl` files are already being created with CRLF on Windows
* so, `git config --global core.autocrlf true` has to be set, to let git do its magic end-of-line normalization on clone/checkin
  * this makes tests, that compare newly generated files with the ones from the repo, succeed
* when comparing metadata files (`fileinfo`), the above solution causes failing tests, because the files from the repo were created from Linux files, whereas the new ones were created from Windows files
  * making this tests pass, would require to generate Linux files on Windows, or create a different set of files in the repo for comparison on Windows

**Comment by joto** [comment]
Okay, this is getting more and more confusing. First, I don't understand why osm/opl files are generated with CRLF. I am using `O_BINARY` to open those files and I just use '\n' to write the line endings!?

Apart from that I think we have to work in this order?
* [ ] What line endings do we want on Windows? I am still unclear about this.
* [ ] How do we make the line endings work in the way we want?
* [ ] How do we get the tests to pass?

**Comment by BergWerkGIS** [comment]
> What line endings do we want on Windows? I am still unclear about this.

Well, if you want stick to the OS specs, it should be `CRLF`.


> How do we make the line endings work in the way we want?

This is indeed interesting.
Could you point me to the source code where the data actually gets written to the files?

Using this snippet, I get `CRLF` with `O_TEXT` and `LF` with `O_BINARY`:

```cpp
	std::string out = "Writing\na new line\nafter\nanother\nTHE END\n";
	//int fh = ::open("test.txt", O_WRONLY | O_CREAT | O_TRUNC | O_TEXT, 0666);
	int fh = ::open("test.txt", O_WRONLY | O_CREAT | O_TRUNC | O_BINARY, 0666);
	::write(fh, out.c_str(), sizeof(char)*out.size());
	::close(fh);
```

So, maybe use `O_TEXT` instead of `O_BINARY`?
Is `O_TEXT` available on *nix?

> How do we get the tests to pass?

I was not successful overriding AppVeyor's git settings for end-of-line normalization for the reference files that are already in the repo, but using the `UNIX2DOS` tool after cloning for converting line endings of `*.osm`, `*.opl`, `*.osc` and `*.osh` the number of failed tests decreased:
https://ci.appveyor.com/project/Mapbox/osmium-tool/build/1.0.90/job/lrvvctcggu8u26kc#L801

Other tests, e.g.: `fileinfo-fi1`, still fail, because the reference files, e.g.: `test/fileinfo/fi1-result.txt`, where created from Unix files, while the test files were created from Windows files.

I'm also unclear on how to proceed here.
Maybe create a second set of reference files created from Windows files.
The tests would have to take into account on which OS they are running and choose the according reference files.

**Comment by BergWerkGIS** [comment]
Oh yeah, and probably `expat` writes `\r\n` transparently when on Windows.
Then you get Windows line endings even when using `O_BINARY`.

**Comment by joto** [comment]
I am not using expat for writing, only for reading.

Files are opened here:
https://github.com/osmcode/libosmium/blob/master/include/osmium/io/detail/read_write.hpp#L80

Linux doesn't have `O_BINARY` or `O_TEXT`, that's why there is the `#ifdef`.

I have [asked a question on the OSM dev mailing list](http://gis.19327.n5.nabble.com/Line-endings-on-Windows-for-OSM-files-td5853103.html). Lets figure out first what we want...

**Comment by joto** [comment]
After the responses on the OSM dev lists I decided to use the same LF line endings on Windows as on Unix.

This needed only a few changes in the code, because we were already opening files with `O_BINARY`. But when we were writing to stdout we still had the conversion. Now stdout is set to binary mode in those cases, too.

All tests now pass on Windows and we can close this issue.
