### ISSUE TITLE
Osmium memory footprint while reading PBF

### ISSUE THREAD

**Issue by wipkirill** [osmcode/libosmium#140]
Hi, I used libosmium for reading PBF files(city extracts) and noticed huge memory allocations in my app. More precisely for a file of 70MB in pbf it uses around 1.6Gb at maximum, average ~600MB. Is it normal behavior in this case? I just need to read osm entities and do indexing and storing coordinates myself in separate storage which uses way less memory. Do I miss some setting to avoid this or PBF format requires so much memory to parse? Please see valgrind profile attached
[valgrind.massif.17340.zip](https://github.com/osmcode/libosmium/files/67723/valgrind.massif.17340.zip)

**Comment by joto** [comment]
Libosmium uses some pretty large buffers (1 to 10 MB usually) to work efficiently, so that's probably what you are seeing here, although the numbers seem a bit too high for that. Libosmium parses the data in several threads and has to keep buffers with the parsed data around until you use them. In the parsed form the data takes about 10 times as much memory as in the very efficiently encoded PBF. For large PBF files this all works out well, but for a 70MB PBF file it might well be that Libosmium has parsed all that into memory before your code even gets to run to work on the data. Without seeing your code I can't say though if you are doing something that makes libosmium get more memory than strictly needed.

There is currently no way to tune those buffers sizes or queue lengths.

**Comment by joto** [comment]
Libosmium `master branch` now uses considerably less memory when reading PBF files. If this is still too much memory, you can use some environment variables to tweak it, but that is difficult and will cost performance. See https://osmcode.org/libosmium/manual.html#run-time-configuration for details.
