### ISSUE TITLE
Invalid XML produced by osmium_convert

### ISSUE THREAD

**Issue by mmd-osm** [osmcode/libosmium#160]
Scenario:

* Use osmium time filter to produce a snapshot file for a particular day, based on a full history input.

`osmium time-filter history-latest.osm.pbf  2010-01-01T00:00:00Z -f osm.pbf > snapshot.osm.pbf`

* Convert snapshot.osm.pbf to .osm: `~/osmium_convert ~/download/snapshot.osm.pbf -t osm 

Around line 534500430 the XML result contains some invalid data:

```
  <node id="410383149" version="1" timestamp="2009-05-24T00:37:11Z" uid="127730" user="Jose Luis Chavez del Cid" changeset="1300686" lat="14.623501" lon="-90.5077762"/>
  <node id="410383150" version="3" timestamp="2009-07-14T06:50:41Z" uid="1417" user="maning" changeset="1823709" lat="14.7446331" lon="120.9721812">
    <tag k="name" v="Meycauayan City Northbound Entry Point"/>
  </node>
  <node id="410383151" version="1" timestamp="2009-05-24T00:37:14Z" uid="127730" user="Jose Luis Chavez del Cid" changeset="1300686" lat="14.6251144" lon="-90.5070399"/>
  <node id="410383152" version="1" timestamp="2009-05-24T00:37:18Z" uid="49785" user="mike67" changeset="1300680" lat="50.767074" lon="6.998428"/>

```

Issue: node 410383150 has a name tag with invalid XML. 

btw: the same error occurs when opening http://www.openstreetmap.org/api/0.6/changeset/1823709/download in a browser.

Last time we had such invalid data, the issue has been corrected in the main db. I'm not sure if that's the right approach or if libosmium should also take care of this?

**Comment by joto** [comment]
This must definitly be fixed in the OSM database. I thought we had taken care of this a long time ago. @tomhughes 

I am not sure whether and how to fix libosmium. I see these possibilities:
* Detect invalid input data and throw an error. This would mean every time there is an error, libosmium becomes useless, even if the error doesn't affect you in your special use case otherwise. But this is the only option that makes sure we will never operate on broken data.
* Detect invalid data only when writing out XML. Because the problem in the data is really only a problem when expressed in XML. Could be rather confusing if it works with PBF but not XML.
* Silently fix the data. Not an option. We can't just change the data. It would break checksums for instance.
* Do nothing. If the API can deliver wrong XML, so can libosmium. Did you check the planet dump, is it invalid also? Or does it remove those characters?

**Comment by mmd-osm** [comment]
I agree that PBF and XML should behave in a similar way. Even now I find it quite hard to exactly tell, which characters are dropped for each output format (XML or PBF on the one hand and planet vs. full history planet, diff files on the other hand). Unfortunately, I couldn't find a planet file for January 2010 anymore. I guess it's somewhat likely that osmosis already filtered them out for an XML based planet.

To get a bit started with the idea of fixing the source of the issue rather than adding workaround everywhere, I ran a small [evaulation](https://github.com/mmd-osm/libosmium/commit/7db5e7cdc4a48cae57aeab68cdea4811e2923a70) on the most recent full history planet and checking for characters below 0x20, excluding tab, CR+LF.

Fortunately, only a very tiny fraction of the overall data seems to be affected, although those few cases are just enough to kill an Overpass API import including those object versions due to invalid XMl data. Manually fixing those is probably an option, right?


```
n410383150 v3 - name = Meycauayan City Northbound Entry Point
n441527354 v1 - name = Meycauayan City Northbound Entry Point
w23751205 v6 - name = Codrii Neamului
w37799039 v1 - name =ирогова
```

**Comment by tomhughes** [comment]
I've fixed those four in the live database.

**Comment by mmd-osm** [comment]
Great, thanks a lot @tomhughes for the prompt reply and fix. I'll close this issue for now and will do a retest once a new full history planet is available.
