### ISSUE TITLE
Creation of <id,OSMObject>-indexes

### ISSUE THREAD

**Issue by Silverspur** [osmcode/libosmium#164]
It looks like the creation of indexes of OSMObjects like `Ways` is not possible due to the privacy of the `Way(void)` constructor. Could I have a confirmation about this?

If this is indeed the case, what should be the way to go for dealing with the following use case:

I need to read a file (storable in memory or not depending on the size), _split the ways into N categories depending on their tags, then for each category loop through its ways_ and do some processing.

Note that it is unfortunately not an option to process the ways directly in the order they are read: the processing must be done category by category.

**Comment by joto** [comment]
The problem is somewhat different. OSM objects can not be created freely, because they are non-standard C++ objects (for performance reasons). You first need a `Buffer` to create them in and then builder objects to actually create them. But in your case the objects all already exist, so this is not the issue.

To keep all the objects you have been reading in memory, you just have to keep the buffers around that you get them in from the `Reader`. Keeping an index is also not a problem: Just keep references (or pointers) into those buffers. The [`ObjectPointerCollection`](http://docs.osmcode.org/libosmium/master/classosmium_1_1ObjectPointerCollection.html) might be something you can use or adapt. A `std::map<object_id_type, OSMObject>` will want to create a copy, but a `std::map<object_id_type, OSMObject*>` will work fine.

Note that keeping all objects in memory is totally feasible for small and medium sized extracts, but probably not for the whole planet. Rule of thumb is: You'll need about 10 times as much RAM as the data needs on disk in a PBF file. If that doesn't work for you, you either have to read in the file multiple times (this is not as expensive as it sounds, so it might be an option you can try) and/or you have to extract some of the information out of the objects and store only that. If, say, you only need the time an object was created, just store the objects Id and the time and throw away the rest. Of course this doesn't work in all cases.
