### ISSUE TITLE
Segfault Buffer::commit(): Assertion `is_aligned()' failed

### ISSUE THREAD

**Issue by mmd-osm** [osmcode/libosmium#167]
After speeding up the [database load process](https://github.com/drolbr/Overpass-API/issues/307) using libosmium already, I'm currently [evaluating](https://github.com/mmd-osm/Overpass-API/commit/563d656d8d77c8ffecbf6be8bc82b6e6f574eac7) how libosmium could also be used for Overpass API PBF output.

While chasing some other bug, I created a [minimum test example](https://github.com/mmd-osm/libosmium/commit/3e3425d856ff7e9a8a94b93db4b8f9dfbc9efc77) along the lines of the OPL input processing in libosmium. Unfortunately, this test example now exhibits a new, unrelated issue:  :confused: 

```
osmium_pbfgen: /home/mmd/libosmium/include/osmium/memory/buffer.hpp:337: size_t osmium::memory::Buffer::commit(): Assertion `is_aligned()' failed.
Abgebrochen (Speicherabzug geschrieben)
```
I could track this down to adding a key / value to a node. Once those two lines are removed, the segfault no longer occurs. 

```C
      osmium::builder::TagListBuilder builder_tag{buffer, &builder};
      builder_tag.add_tag("key", "value");
```
I'm wondering, if I'm doing something completely wrong with the way I'm creating PBF files. Looking through the documentation & examples, I was a bit puzzled what the recommended approach would look like to create PBF files (written to stdout) from scratch.

Thanks a lot for looking into this!

BTW: Environment is Ubuntu 16.04, x64.

**Comment by joto** [comment]
The problem is that the `Builder` classes do something in their destructors: The destructors make sure that the alignment ist kept and sizes are correct. So you have to make sure those destructors are called before doing anything else, ie before calling `commit` on the buffer. The easiest would be in your case to add a scope around the `NodeBuilder` and around the `TagListBuilder`.

There is another problem in your code: Calling `builder.add_user()` invalidates the `node` reference. So you have to add the location before the user name (or call `builder.object()` again).

Because of these difficulties, the recommended way these days for programmatically creating OSM data is through another interface. Unfortunately that isn't documented yet, but you can see the tests at `test/t/builder/test_attr.cpp` which should be mostly self-explanatory. This way you don't have to know about the internals.

**Comment by mmd-osm** [comment]
Your analysis was spot on! In my minimum example, I somehow removed the scoping for the TagListBuilder, which triggered a nice new bug. Never thought about the destructor in the first place, which of course gets called, when leaving the scope  of the local variable. Also, the tricky dependency for `builder.add_user()` is very good to know.

As recommended, I switched to a different interface now. The test cases in `test_attr.cpp` were indeed very useful and could be adapted fairly easily to what I needed.

Thanks to your kind support, there's now `[out:opl]` and `[out:pbf]` available in Overpass API, at least as a prototype, two new formats with really little effort. Now, we only have to convince Roland that we definitely need libosmium... :smiley:   @drolbr 

Here's an example using  `opl` output: http://overpass-turbo.eu/s/joC 

 (`out meta;` is mandatory at this time, but I expect this restriction to be lifted some time in the future. Also, the osmosis replication timestamp is still hardcoded in PBF output.)
