### ISSUE TITLE
Models for Container Concept

### ISSUE THREAD

**Issue by daniel-j-h** [osmcode/libosmium#169]
Some (if not all) `libosmium` container are not models for the Container concept:

http://en.cppreference.com/w/cpp/concept/Container

See e.g. the `WayNodeList` which could fulfil this concept easily.

Is there a reason for this? Can you make all container proper Container models?

Context: I'm trying to register some `libosmium` classes and the wrapper-generator assumes everything iterable (`begin` / `end`) also provides e.g. `value_type`. Now we can discuss if this is a good idea in the first place but that's how it is at the moment.

**Comment by joto** [comment]
I don't think we can be fully compatible with the Container concept or other concepts in many cases. For instance you can't just copy a `WayNodeList` because it has to live in a `Buffer`, but I think this would be requiered from looking at the page you linked to. But that doesn't mean we can't implement everything that we can and that might be useful. I have done this in some cases (for instance `WayNodeList` has an `iterator` typedef, but only where I needed it or was aware that it might be useful.

I am not sure it makes sense to do this systematically, because, as mentioned, I don't think we'll be 100% compliant anyway, but I have added some typedefs to `NodeRefList` and `memory::Collection`.
If you need more, ask or send pull requests.

**Comment by daniel-j-h** [comment]
I see, copying is not possible because of impl. details and blocking here.

Thanks for adding the typedefs - in the meantime container detection was fixed in the wrapper-generator.

Closing as not actionable.
