### ISSUE TITLE
Using libosmium Writer & stdout along with FastCGI

### ISSUE THREAD

**Issue by mmd-osm** [osmcode/libosmium#174]
While producing PBF output in a CGI program via *stdout* works like charm, I'm struggling with the corresponding FastCGI variant.

One of the possible approaches I'm currently using to return some output from a FastCGI program is outlined on the following blog post: basically, the streambufs for cin/cout and cerr are redirected to those provided via the FastCGI library. Any subsequent use of `cout << ` will then automatically end up in the FastCGI output. This is pretty convenient, as I don't have to change large parts of the coding.

See http://chriswu.me/blog/writing-hello-world-in-fcgi-with-c-plus-plus/

Applying the same logic to libosmium does not seem to work out of the box:

```C
      output_file = new osmium::io::File("", type);    // use stdout
      header = new osmium::io::Header();
...
      writer = new osmium::io::Writer(*output_file, *header);
```
This has the somewhat unexpected effect, that the PBF output itself ends up in /var/log/apache2/error.log rather than being sent to my browser.

So far, I have found out that osmium::io:detail directly refers to file descriptor 1 for stdout and also directly writes to this file descriptor (see [this link](https://github.com/osmcode/libosmium/blob/6523bae108c66221a7e3eb7ad5348b053a1af7db/include/osmium/io/detail/read_write.hpp#L135)).

I wonder what would be a good approach to make libosmium either
* use a streambuf for output (like the cout.rdbuf(...) approach in the blog post), or 
* to use `std::cout` rather than the more lower level `::write`.

Again many thanks for taking the time to look into this.

**Comment by joto** [comment]
Osmium uses the file descriptors directly, because it does its own buffering. The stream interface would just use an additional copy making everything slower and use more memory.

I am not sure what the best approach in your case would be. Here are some ideas:

* In some way the FCGI library must use a file descriptor internally, too. Maybe you can get to it. Then we'd have to change libosmium that it could take any file descriptor (instead of just the magic "-" file name which means fd 1). Or, maybe you can move that file descriptor using `dup2` to fd 1 and it would all work. If the FCGI lib does more with the data than just writing it to a socket, this approach will not work.
* You could write a new "backend" for libosmium that writes the data to a stream instead of to the file descriptor. This is doable, but not that easy, because the output code is mixed up with the gzip/bzip compression code.
* The Reader already has the option of reading from a char array instead of from a file descriptor. We could add the same functionality to the Writer. The main programs job would it be then to setup a buffer of the right size, call the Writer and then copy the buffer into the stream. But that's an additional copy and there is also the issue of how big the buffer needs to be etc.

**Comment by mmd-osm** [comment]
Thanks a lot for your very detailed feedback! I analysed all three options in terms of feasibility, efforts and to some extend also risk.

* Unfortunately, this approach does not seem to work for exactly the reason you mentioned in your last sentence: FastCGI adds some binary header to each message, and writing libosmium output directly to a fd would break this binary protocol.
* This option sounds interesting, but I was a bit worried on the implications and effort involved. I tried something similar (actually cheating a bit) and modified `read_write.hpp` so that it writes directly to `cout`, rather than taking some streambuf into account and properly expose it in the API.  This worked quite well in my tests so far. However, my preference would be an unmodified libosmium lib, so I'm not quite sure how to proceed here, or if it makes sense to have this additional backend in the core library.
* The drawback with the option is clearly the preallocated buffer. In my use case, I don't know upfront how large the memory requirements might be, and they could be easily in the range of several 100MB. 

I came up even with a 4th option: using a named pipe and a dedicated thread, which collects libosmium results and feeds it back into `cout`. This sounds a bit crazy, it has some overhead due to copying, etc., but seems to work, and doesn't require changes to libosmium AFAICS. For reference, if have commited the [code here](https://github.com/mmd-osm/Overpass-API/commit/2e8a78d18f6f7be8d9968a6f19a7c429b314ba7d).


```
--- a/include/osmium/io/detail/read_write.hpp
+++ b/include/osmium/io/detail/read_write.hpp
@@@ -125,6 -125,6 +125,14 @@@ namespace osmium 
               * @throws std::system_error On error.
               */
              inline void reliable_write(const int fd, const unsigned char* output_buffer, const size_t size) {
++
++                if (fd == 1)
++                {  
++                   const char* buffer = reinterpret_cast<const char*>(output_buffer);
++                   std::cout.write(buffer, static_cast<unsigned int>(size));
++                   return;
++                }
++
                  constexpr size_t max_write = 100L * 1024L * 1024L; // Max 100 MByte per write
                  size_t offset = 0;
                  do {
@@@ -155,6 -155,6 +163,11 @@@
              }
  
              inline void reliable_fsync(const int fd) {
++                if (fd == 1)
++                {
++                   std::cout << std::flush;
++                   return;
++                }    
  #ifdef _WIN32
                  if (_commit(fd) != 0) {
  #else
@@@ -165,6 -165,6 +178,8 @@@
              }
  
              inline void reliable_close(const int fd) {
++                if (fd == 1)
++                  return;
                  if (::close(fd) != 0) {
                      throw std::system_error(errno, std::system_category(), "Close failed");
                  }
```

**Comment by joto** [comment]
Well, going through a pipe is not really an option I would argue. Bad enough that you are using FastCGI which means there is additional overhead compared to a solution in the web server directly, we don't need to make this worse. :-)

I'd be willing to consider a solution that would change libosmium so it could work with streams in some way. To do this in a clean way, I would think, we'd need a version of the `osmium::io::File` constructor that takes a stream instead of a file name. This could then be used to create the Reader etc. I'll have to look at the code some more to see whether that's possible and what needs to be done to make this work.

**Comment by mmd-osm** [comment]
> Bad enough that you are using FastCGI which means there is additional overhead compared to a solution in the web server directly,

Well, the current implementation is based on CGI, which makes it next to impossible to reuse buffers across several requests/queries. Also, there's some fix cost for each call. FastCGI is similar enough to CGI to have only very minor impact on the current implementation. Also, the overhead is fairly ok to the point that it's not a bottleneck in any way. A wide range of different web servers support this model out of the box, like Apache, Nginx, etc. Also, Cgimap is based on FastCGI so it can't be completely unusable. :-)

Putting C++ code directly in the Apache web server would probably mean to have some Apache module or to expose some own Web server. Both have some disadvantages, e.g. too tight integration to Apache in case of a module.

> I'd be willing to consider a solution that would change libosmium so it could work with streams in some way.

Great, that's awesome!

**Comment by mmd-osm** [comment]
I believe for our purposes it would probably be more than sufficient to be able to provide an alternative implementation for read_write.hpp, i.e. defining some abstract base class for those 6 functions and use them as default implementaion. Also, Writer would need some way to tell the Compressor that you want to use your own implementation instead. Maybe open_for_reading should be excluded from such an abstract base class, as it doesn't really fit here.

This way you don't have to introduce streams in the normal processing flow and at the same time would offer maximum flexibility. There's a tiny bit more overhead to call those methods.

I didn't look at the reading side of things, though, so cannot comment in this.

**Comment by joto** [comment]
This comes awefully close to some huge generic IO framework that I don't want to write. For this to work we need some generalized "handle" that could be a file descriptor (as in the current code) or a stream or so. All the code that uses the fd currently has to be changed to use that generic handle. And, as you mention, all the code starting from the Reader or Writer gets extra parameters (and maybe even template parameters if we want to avoid virtual calls.) This would be quite a significant rewrite.

Then there is the problem that some of those functions you mention are also used outside the normal IO stuff for writing indexes to disk. I'd have to change that code, too.

I am thinking a bit in a different direction: For reading there is already the option of reading from a buffer instead of from a file. This [buffer](https://github.com/osmcode/libosmium/blob/master/include/osmium/io/file.hpp#L78-L79) is used [in the Reader](https://github.com/osmcode/libosmium/blob/master/include/osmium/io/reader.hpp#L251-L253). Something similar could be done on the writer side. Problem is: Reading from a fixed size `char*, size` is easy, but writing to a buffer needs some kind of dynamically sized buffer that grows or is flushed and all that. And I don't know how to do this without including some huge machinery. I admit that the way Osmium handles reading from a buffer is a bit of a hack, but it hides all this from the user who doesn't need it. I a way, the `File` class acts as the handle I spoke about at the beginning of this comment, but unless a real handle it only represents the "data", not an open file or stream. The file descriptor isn't part of the `File` class. I am not exactly sure how to make this work more generically.

**Comment by mmd-osm** [comment]
Hmm... this all sounds like a lot of work and implications on the current code line to support requirements for just one project. Unless there are other projects with similar requirements, I would suggest to put this issue "on hold" for the time being.

With the admittantly somewhat ugly workaround outlined above, we can create pbf/opl output as of today. At some point in the future, we can still move to a saner approach.

Demo: http://overpass-turbo.eu/s/pSq (pbf), http://overpass-turbo.eu/s/pSr (opl)
