### ISSUE TITLE
Remove utf8 dependency from string util

### ISSUE THREAD

**Issue by daniel-j-h** [osmcode/libosmium#211]
The string util header currently has a dependency on the utf8cpp library and needs the user to bring it in completely. There are some other debug and opl headers with the utf8cpp library dependency but they're not as commonly used I would say.

https://github.com/osmcode/libosmium/blob/master/include/osmium/io/detail/string_util.hpp#L43

From what I can see there the utf8cpp dependency is only ever used to to extract the (up to) 4 byte unicode code point out of an iterator to 1 byte chars.

Can we write a small function that does this for us and get rid of the utf8cpp dependency in the string util header? The string util header gets included transitively from other commonly used headers.

- https://en.wikipedia.org/wiki/UTF-8#Description
- https://github.com/ledger/utfcpp/blob/2233ec933f5661c7050b94d3b14f5f9f51ae3d55/source/utf8/unchecked.h#L60-L89

**Comment by joto** [comment]
It might not look like there is a lot of code there, but it is fiddly code that would need a lot of testing. Also there is [another place where utfcpp is used](https://github.com/osmcode/libosmium/blob/master/include/osmium/io/detail/opl_parser_functions.hpp#L158) in libosmium that we'd also have to fix for this to make sense.

So this is a lot of work to get rid of this dependency. Unless somebody is willing to do the work and provide well-tested replacements for the functions needed from utfcpp, this is unlikely to happen. Especially since there are Debian and Fedora packages available for utfcpp which will be enough for most users.
