### ISSUE TITLE
Negative OSM object version numbers in PBF files

### ISSUE THREAD

**Issue by Nakaner** [osmcode/libosmium#245]
If a PBF file contains an OSM object with a negativ version (e.g. -1), Osmium throws `PBF error: object version must not be negative`. Such files are produced by Osmosis if it has no metadata.

Both the `Info` and the `DenseInfo` message in the OSM Protobuf format description [permit](https://github.com/scrosby/OSM-binary/blob/master/src/osmformat.proto#L137) negativ integers (they use the `int32` type which is not efficient for negativ numbers) and the default is even `-1`.

Osmium uses `uint32_t` for version numbers. Therefore any negative numbers (they are a sign that something went wrong) have to be converted to 0. Shall I write a pull request which does that or do we want to blame Osmosis?

**Comment by joto** [comment]
Again one of those things that were never defined properly so nobody knows... Do you see any other negative version numbers apart from -1? I can see that -1 could stand for "unknown", although I would use 0 as "unknown", because real version numbers start at 1. But if there are other negative version numbers, maybe we need to differentiate between them in some way.
