### ISSUE TITLE
IdSetDense: estimate expected size

### ISSUE THREAD

**Issue by mmd-osm** [osmcode/libosmium#272]
For performance reasons, I want to dynamically choose between IdSetDense and the binary search based IdSetSmall. Besides runtime, memory efficiency is also important, and here IdSetDense has the disadvantage that 64bit node ids might cause rather high memory consumption depending on how node ids are distributed.

The only option I have today is to feeding data into my dense idset, and determine the memory consumption by calling `used_memory()`. I have some doubts if this 'after-the-fact' approach makes sense. In my use case, I start with a vector of ids, and want to decide based on different criteria if it's worthwhile switching to IdSetDense.

```
  void populate_ids_dense(const std::vector< typename Object::Id_Type >& ids_) {
    if (ids_.size() > 1000) {
      for (auto & id : ids_)
        ids_dense.set(id.val());
      use_dense = true;
    }
```

What I'm looking for is some kind of `estimate_memory_consumption` method, that takes a begin and end of an iterator, calls `chunk_id(id)` for each entry, and returns the memory consumption based on the number of distinct _chunk_ids_ and _chunk_size_. 

By the way, did you run any performance measurements as to which implementation (bitset vs. binary search) is faster under different circumstances? If so, I'd be very interested in a bit more detail.

**Comment by joto** [comment]
First, the big difference is that `IdSetSmall` only works efficiently if you have different "phases" in your application, first writing IDs, then later looking them up after calling `sort_unique()`. If reading and writing IDs is interleaved, you can use the linear search, but this will be horribly inefficient. So for these cases you have to use `IdSetDense` even for smaller datasets.

Performance for `IdSetDense` is much better than `IdSetSmall` for anything but the smallest datasets, so if you have the memory, you probably want to use it. This is because the performance bottleneck here is memory access. For `IdSetDense` you only need one access into the chunk table (probably cached) and one access into the data itself. For `IdSetSmall` several accesses are needed to do the binary search.

Now for the `estimate_memory_consumption` function that you ask for. I don't really see the point. You can estimate the sizes using simple arithmetic provided that your ids are somewhat randomly distributed, that should be good enough. Doing more work here pretending to fill the data into an IdSet creating statistics is just a lot of extra work. Now ideally we had some magic thing that will keep those statistics while adding data and switches the internal representation based on that. But somebody would have to write and test that.

So my recommendation here is: Use `IdSetSmall` with linear search for very small sets (<<100), use `IdSetSmall` with binary search (if you can) for slightly larger sets and `IdSetDense` for anything else. You have to benchmark yourself to see which one behaves best for you application, your datasets and your hardware if you have an "in between" case.

**Comment by mmd-osm** [comment]
> I don't really see the point. You can estimate the sizes using simple arithmetic provided that your ids are somewhat randomly distributed, that should be good enough.

Well, that was my original intention. However, as all of the IdSetDense implementation details are private for a good reason, and I didn't want to break encapsulation nor replicate any existing code found in IdSetDense, having something like `estimate_memory_consumption` seemed to be the least intrusive way to get to this information: here's a bunch of ids, just tell me how much memory they would take up.

I agree that memory consumption is usually not the biggest concern, especially for a single process. This may be a bit different in a server environment with multiple concurrent queries and limited per user memory. The idea was to have some easy means to better assess memory consumption upfront, and avoid a worst case scenario with 500 - 1000 ids already triggering >2GB total memory allocations. If that value exceeds some threshold (subject to further benchmarking), falling back to binary search could be an option to still fulfill the user request.

**Comment by joto** [comment]
What I mean is that you have to estimate this "offline", ie. you have an idea what the data for your application looks like so take piece of paper and do a rough calculation. This tells you whether the application you have with the data you have will fit into your hardware. Having this implemented in your application doesn't help, because it is too late then. If the data doesn't fit, all the application can do is tell you that it doesn't fit, but you would notice that anyway when you actually do the work.

If you want to implement something clever that "scales" automatically, then do so from scratch. Well, you can use the ideas from the current code and re-use the code if it makes sense. But that way you can keep all the statistics you need and get the best and most performant implementation. This seems easier to me than trying to build something that sits on top of existing code trying to second-guess what it does.

**Comment by mmd-osm** [comment]
Maybe that's a good time to go back to the drawing board and think about the issue in a more general way (which hopefully makes this discussion a bit more relevant for libosmium).

For a somewhat sparsely populated IdSetDense (having 1k - 1M node ids maybe), chances are we're allocating quite a number of 4 MB chunks, although they might only contain a very small number of "1" bits. This has implications on the total memory consumption, on the time spent on memset, but also on the IdSetDenseIterator, which has check every single allocated byte.

I'm wondering if the current default of 22 bit `chunk_bits` isn't actually too small as the comment in the code suggests but rather _too large_ for my use case.

I did some initial testing comparing 22 bits vs. 16 bits. For one test case, this reduced memory consumption from 770MB down to 240MB with a negligible CPU time improvement. Of course this needs much more testing.

As there's no clear "one size fits it all" value, my proposal for libosmium would be to expose `chunk_bits` as a template parameter with a default value of 22. This way, it would be very easy for a libosmium user to adopt this class to different use cases.

```
experimental::IdSetDense<typename Id_Type::Id_Type, 16> tmp_ids;
```


```C++
  template <typename T, unsigned int L = 22>
  class IdSetDense : public IdSet<T> {

      static_assert(std::is_unsigned<T>::value, "Needs unsigned type");
      static_assert(sizeof(T) >= 4, "Needs at least 32bit type");
[... add static assert for L as well ... ]

      friend class IdSetDenseIterator<T, L>;

      // This value is a compromise. For node Ids it could be bigger
      // which would mean less (but larger) memory allocations. For
      // relations Ids it could be smaller, because they would all fit
      // into a smaller allocation.
      constexpr static const std::size_t chunk_bits = L;
      constexpr static const std::size_t chunk_size = 1 << chunk_bits;
```

**Comment by joto** [comment]
Well, you should use `IdSetDense` only for dense sets, that's why it has that name. For 1M node IDs, the `IdSetSmall` uses only 8MBs. That's far better than the 240MB even your changed code uses.

There is the somewhat difficult case where you have a medium sized set but still need to do interleaved read and write accesses. This isn't supported well with `IdSetSmall`, but I'd try with a `std::set` first and see how that fares.

**Comment by mmd-osm** [comment]
I was about to post some test results. Well, never mind.

**Comment by joto** [comment]
@mmd-osm Sorry, hadn't heard anything back, so I thought the matter is closed.

**Comment by mmd-osm** [comment]
Thanks! I just wanted to write a few words on my test findings...

First of all, the main idea behind using dense sets is described in much more detail here: https://github.com/drolbr/Overpass-API/issues/473. For some test cases, the current binary search + sort based approach results in some long run times, and also, the memory footprint is quite high.

One very common pattern for tag key/value filtering is, that an unknown number of entries needs to be added to a vector for the first filter criterion, the vector gets sorted afterwards, and in the next iteration, we'll check, if any of the existing entries in our vector match the osm ids or the second tag, etc. That's pretty much a classical set intersection problem.

By using dense sets (or bit vectors in general), I wanted to leverage O(1) access times for dense sets, and of course, get rid of having to sort the vector after each iteration. The downside of this approach is, that we might be using much more memory, and O(1) vs. O(log n) for binary search + O(n log n) for sorting won't make much of a difference in terms of runtime for small vector sizes.

I started playing around with a hybrid approach, where we start adding entries to the vector, and migrate the vector contents to a dense set, once we hit some threshold value.

See source code: [perftest.txt](https://github.com/osmcode/libosmium/files/2646251/perftest.txt)



```
[timeout:3600][maxsize:5000000000];
way[building][source][name][height][!"addr:housenumber"];out;
```

Before:
	User time (seconds): 81.46
	System time (seconds): 3.39
	Percent of CPU this job got: 99%
	Maximum resident set size (kbytes): 4229688

After:
	User time (seconds): 32.28
	System time (seconds): 0.99
	Percent of CPU this job got: 98%
	Maximum resident set size (kbytes): 377384

**Comment by joto** [comment]
@mmd-osm I am not sure what this is telling us beyond "dense sets are good for large datasets, small sets are good for small ones, hybrids can be good when we don't know how large the dataset is"?

If I understand this correctly the table shows the timing summarized over different data set sizes? This hides the information for which data set size which one is best, that would be interesting. And it probaly influences the `chunk_bits` setting. The `chunk_bits` are not optimal for small data set sizes, we know that. But for larger sizes, larger `chunk_bits` settings should be better.

I have just pushed code to master that makes the `chunk_bits` configurable (at compile time) while being backwards compatible to the old code. So if somebody wants to change this from the default, they can do so.

Btw: You have a string copy inside your `ExecutionTimer` constructor, which will throw the timing off. Doesn't matter in this case probably, but might in others when you are timing shorter durations.

**Comment by mmd-osm** [comment]
> If I understand this correctly the table shows the timing summarized over different data set sizes? This hides the information for which data set size which one is best, that would be interesting

Right, I only posted the results from the pivot table, which includes a summary over a larger number of measurements. I will attach the raw measurements as well. The test program includes the number of set and get values, measurements in µs for small, dense, and hybrid, as well as the respective memory consumption.

Regarding memory consumption: I wasn't sure if my code change in `used_memory` for dense memory would be correct. My understanding was that as long as a chunk doesn't have any bt vector assigned, it shouldn't consume any memory. Today, `used_memory` would assume all chunks to hold a vector, even though it hasn't been allocated yet.

**Comment by joto** [comment]
The chunk_bits were chosen based on the assumption that most chunks would be used, because the implementation of `IdSetDense` only makes sense in that use case. That's why I don't think making the chunks smaller would matter much. The idea was never that a sizable number of the chunks would be kept empty. If many of the chunks are empty, it also means that those that are not empty would only contain very little data, which defeats the purpose of the `IdSetDense` implementation. This assumes the ids are not clustered much but reasonably "random", which is generally the case from my observation.

That's also why the `used_memory` function is implemented the way it is. It is fast and easy to calculate a rough estimate that way. For normal operation it doesn't matter much whether the value is off by 10% or so.

**Comment by mmd-osm** [comment]
> This assumes the ids are not clustered much but reasonably "random", which is generally the case from my observation.

I haven't really done an in-depth analysis how osm object ids are distributed. Although I'm assuming a uniform distribution in my test script, some large scale events, such as the ODbL license change redaction might skew those numbers a bit. Some key/value pairs might become increasingly popular or diminish over time, which again could impact the distribution. I will keep an eye on this point.

> That's also why the used_memory function is implemented the way it is.

Ok, this makes sense. I wasn't sure if I'm missing something here.

By the way, I have uploaded the raw measurements here for now: https://dev.overpass-api.de/tmp/psv/perf_smalldensehybrid.ods

**Comment by joto** [comment]
I agree that the IdSet* implementations in libosmium are somewhat simplistic and not all that great. But they work for many use cases and I don't see that we'll implement something much better at the moment. And any user of libosmium can always implement their own specific to their needs. So I am closing this here.

**Comment by mmd-osm** [comment]
Just wanted to add a quick comment how this is solved in Roaring Bitmaps (http://roaringbitmap.org/). Instead of going full scope with either Bitmaps or Vector, they use a more nuanced hybrid strategy and make that decision on a chunk-by-chunk level.

In case of a vector, they take advantage that each chunk has a certain offset or base value, i.e. a 64bit value can be stored as a 32 bit (or even 16bit) value, leveraging the offset value to calculate the resulting id value.

I find their research paper https://arxiv.org/pdf/1603.06549.pdf very interesting, in particular chapter 4 on pages 4-6 give a very good overview. Runlength encoding is probably less relevant for OSM, but bitmap and array containers are.
