### ISSUE TITLE
Conversion warning on Windows32 in vector_map.hpp

### ISSUE THREAD

**Issue by lonvia** [osmcode/libosmium#288]
I see these warnings when compiling [osm2pgsql under Windows x86 on Appveyor](https://ci.appveyor.com/project/openstreetmap/osm2pgsql/builds/27761074/job/05s0jonqk5c9gklt):

```
C:\osm2pgsql\contrib\libosmium\osmium/index/detail/vector_map.hpp(98): warning C4244: 'argument': conversion from 'const osmium::unsigned_object_id_type' to 'const std::size_t', possible loss of data
C:\osm2pgsql\contrib\libosmium\osmium/index/detail/vector_map.hpp(94): note: while compiling class template member function 'osmium::Location osmium::index::map::VectorBasedDenseMap<osmium::detail::mmap_vector_file<osmium::Location>,osmium::unsigned_object_id_type,osmium::Location>::get_noexcept(const TId) noexcept const'
        with
        [
            TId=osmium::unsigned_object_id_type
        ]
C:\osm2pgsql\node-persistent-cache.cpp(11): note: see reference to class template instantiation 'osmium::index::map::VectorBasedDenseMap<osmium::detail::mmap_vector_file<osmium::Location>,osmium::unsigned_object_id_type,osmium::Location>' being compiled
```

It might also be that osm2pgsql uses libosmium badly. Needs investigation.

**Comment by joto** [comment]
Osmium doesn't fully support 32 bit systems. Some functions will work, others will not work with OSM object ids larger than 2^31-1. This isn't really consistent and I don't know myself what exactly the behaviour will be in every case. I am not using any 32bit systems myself and it is doubtful whether anybody will actually work with OSM data on 32bit systems due to the memory constraints there. The [documentation](https://osmcode.org/libosmium/manual.html) mentions possible problems on 32bit systems. I haven't heard any actual complaints so I believe nobody is using Osmium on 32bit systems, so I don't see that we'll spend any effort on fixing this.

**Comment by mmd-osm** [comment]
I added a comment about compile time checks for 64bit systems here: https://github.com/openstreetmap/osm2pgsql/pull/1006#issuecomment-560089964 and now found this issue.

As people tend to not read any documentation at all, issuing a compile time warning on a 32bit system seems like a sensible thing to do to me. People might still ignore it, but you would spot it immediately in a build log.
