### ISSUE TITLE
libosmium will no longer build with upcoming PROJ 7.0

### ISSUE THREAD

**Issue by rouault** [osmcode/libosmium#295]
PROJ 7.0 planned for March 1st 2020 will remove proj_api.h that libosmium depends on. The removal pf proj_api.h is imminent per https://github.com/OSGeo/PROJ/pull/1872.  PROJ documentation has a number of hints to help for the migration: https://proj.org/development/migration.html

**Comment by sebastic** [comment]
See also: #277

For which `ACCEPT_USE_OF_DEPRECATED_PROJ_API_H` was added.

**Comment by joto** [comment]
The problem is that the new Proj API is sufficiently different from the old Proj API that I would have to break the libosmium API to use it efficiently. This means a breaking change for libosmium users at which point I am asking myself whether it is worth it. Libosmiums proj support is basically just some convenience functions not used by anything major inside libosmium.

Users can then either stick with the old Proj versions (I hope distributors will continue shipping those for years to come) or change their code to use any Proj version they like directly, ignoring the now obsolete libosmium functions.

The alternative is to add a whole new projection API to libosmium which supports the new and old Proj libraries giving users a migration path. But that is a lot of work. The only reason really that Libosmium has support for Proj is that it wraps the C functions in C++ which is much easier to use. But that should be solved by having a Proj++ wrapper (ideally supported by the Proj project) that does this.

**Comment by rouault** [comment]
Pending a proper support for proj.h, would a minimalistic hack that would consist in just supporting the 2 hardcoded paths for EPSG:4326 and 3857, so without any PROJ use, would be acceptable ? All other methods would just error out. That would at least unbreak compilation issues

**Comment by joto** [comment]
@rouault Not sure what you mean. Because libosmium is a header-only library and the proj-specific parts are optional, there isn't really any compilation that breaks. The tests look for proj but should simply not compile and run the tests that need proj if it isn't available.

**Comment by rouault** [comment]
> Because libosmium is a header-only library

I missed that...  So maybe have a OSMIUM_USE_PROJ_VERSION define that could be set to 0 or 4:
- 0 == do not use PROJ 
- 4 == use PROJ.4 proj_api.h
- And some day, 6 == use PROJ.6 proj.h API could be supported

**Comment by sebastic** [comment]
Of the projects that rely on libosmium in Debian, only osm2pgsql uses `projection.hpp`. So that would break without it.

**Comment by rouault** [comment]
What is quite annoying is that projection.hpp exposes in its API the no-longer-existing-in-proj-dot-h projPJ structure in the CRS::get() method ( https://github.com/osmcode/libosmium/blob/master/include/osmium/geom/projection.hpp#L98 ) and this is used by https://github.com/openstreetmap/osm2pgsql/blob/4939dd9024846e233a0a0ae3dcf48218eddc05d8/src/reprojection.cpp#L104. So making the use of projection.hpp in osm2pgsql is probably the cheapest fix.

**Comment by joto** [comment]
I have now written the code (in branch `proj6-support`) in libosmium in a way so that it works with the old and new APIs using a macro to switch between them. (I still have to deprecate part of the API that I can't replicate in PROJ > 6, but the most important part is still available.)

But now I don't know how to automatically set that macro with CMake. Because of all the backwards/forwards-compatibility I can't just decide this based on the existence of `proj.h` or `proj_api.h`. There must be somebody who has already written the magic to make this happen? Any suggestions?

I looked at https://proj.org/development/cmake.html but that isn't really helpful, because I can't rely on that config being available on the system, it isn't on any I have.

**Comment by sebastic** [comment]
May I suggest not including a major version in the defines?

 * `OSMIUM_USE_PROJ_H` (PROJ >= 6)
 * `OSMIUM_USE_PROJ_API_H` (PROJ <= 5)

This mimics the naming of `ACCEPT_USE_OF_DEPRECATED_PROJ_API_H` in PROJ itself.

Regarding the CMake bit, having and option like `USE_DEPRECATED_PROJ_API_H` that when enabled uses `add_definitions(-DOSMIUM_USE_PROJ_H)` and `add_definitions(-DOSMIUM_USE_PROJ_API_H)` otherwise may work.

**Comment by joto** [comment]
I have added this to master now. The CMake config will figure out what version you have installed. If `proj_api.h` is available, it is used, otherwise `proj.h`. I had to do it this way around, because the new API doesn't work in version 5, so it sticks with the old API as long as it is available.

**Comment by joto** [comment]
@rouault looked at the code and found some potential problems (see comments on [this commit](https://github.com/osmcode/libosmium/commit/d5a76e635feddde961db775810708528eeaebf0f). 

Thanks @rouault for trying to help, but it seems using the new API is even more complex than I had thought. I am cutting my losses here and will pull out the new projection code again. I don't know of anybody using it anyway, and it doesn't make sense to put something in that might not work correctly.

**Comment by joto** [comment]
I have now reverted the change that introduced the support for the new PROJ API due to the potential problems with it that @rouault found. I have moved that code to a new repository https://github.com/osmcode/osmium-proj so it is not lost and people can use it from there if needed or copy it into their own code and change as needed.

It is, after all, just a little bit of code to adapt libosmium to PROJ and doesn't need to be in libosmium itself. It is in no way central to what libosmium is doing. I have marked the old PROJ code in libosmium as deprecated and will remove it in a later version.

**Comment by jmckenna** [comment]
@joto thanks for your efforts.  Can you also announce this new repository, such as on [osm-talk] or [tile-serving] lists, as a general call for contributors?  I believe there are many users out there who leverage libosmium's PROJ support (but likely don't realize they depend on it, to display their OSM data in other projections).  Again thank you for trying so hard on this.
