### ISSUE TITLE
pbf_output_format: sort StringTable by frequency?

### ISSUE THREAD

**Issue by simon04** [osmcode/libosmium#318]
As far as I can tell from the pbf_output_format implementation, and manually inspecting the first few StringTable entries in GeoFabrik's austria-210101.osm.pbf, the StringTable entries are in FIFO order.

The Java implementation of OSM-binary documents how sorting the StringTable by frequency is used to save space (since integers 1–127 can be PBF-encoded with 1 byte), see https://github.com/openstreetmap/OSM-binary/blob/1c7fadcde883300047275dcbb87fcedf385c5030/src.java/crosby/binary/StringTable.java#L60-L91

In the libosmium code I couldn't find any reference why this concept is not used…

**Comment by joto** [comment]
Sorting the entries is done to make them a bit better to compress, but I tested this and the advantage is tiny. On the other hand the sorting adds a huge overhead, because all references to those strings need to be updated, which needs another pass over all data in a block. That's why I decided to not implement it this way.

**Comment by simon04** [comment]
Thank you for the explanation. I assumed that the sorting was left out for a reason. :-)
