### ISSUE TITLE
Please reconsider the fadvise() usage

### ISSUE THREAD

**Issue by account-login** [osmcode/libosmium#335]
Hello, I've encountered unexpectedly high disk io usage when processing pbf files. I have located the source of the problem is that libosmium actively discarding page cache with `POSIX_FADV_DONTNEED` (https://github.com/osmcode/libosmium/search?q=POSIX_FADV_DONTNEED).
Discarding page cache for a file is fine only when the file will never be used again, I don't think this is an assumption that a library can make. Also, the page cache is a shared resource, discarding page cache can hurt other app's performance if the file is used by other apps (like running parallelled processing on the same file).
I removed the `fadvise` call and my workflow became much faster. I suggest remove it, or make an optional flag to enable it.

**Comment by joto** [comment]
Interesting. In my tests the fadvise improved performance, because the memory could immediately be used for something else. I assumed it wouldn't hurt because either the kernel doesn't need more memory in which case the `fadvise` basically should be a noop, or it would need some memory in which case it makes sense to release the memory for a large file instead of forcing something else out. But I didn't consider the parallel reading use case.

I have to think about how to best solve this. Probably an environment variable.

**Comment by joto** [comment]
This is now available in master. Set `OSMIUM_CLEAN_PAGE_CACHE_AFTER_READ` to `no` to disable the fadvise.
