### ISSUE TITLE
I/O: remote .osm.pbf datasets with HTTP GET byte-range requests

### ISSUE THREAD

**Issue by daniel-j-h** [osmcode/libosmium#377]
Hey folks this is more of a feature request or food for thought but I still wanted to raise it to bounce some ideas back and forth:

Can we get remote dataset support in osmium and use byte-range requests so that users don't have to download a big file first?

**Context:** We're seeing the Overture Maps folks distributing their data in (Geo)Parquet files which can then be read from a remote (e.g. an AWS S3 bucket or any other static host) via http requests in parallel and http get byte-range requests allow to skip unused data. The Protomaps folks are doing the same to download only the vector tile data needed on the fly from a single file.

I was wondering if a similar design would work with the .osm.pbf format and libosmium
1. From what I understand the .osm.pbf format already supports random reads on fileblock by fileblock basis
2. It looks like libosmium already supports multiple I/O subsystems and maybe a curl based http get byte-range one would fit in there

Example use cases of what I have in mind here:
- When I want to use osmium extract to cut out a very small region in DR Congo I need to download a 400 MB .osm.pbf snapshot
- When I want to use osmium tags filter to extract e.g. only ways with a specific tag I need to download the same big file first

I only have a limited understanding of the .osm.pbf file format and libosmium internals but in those cases would a http get byte-range request based I/O subsystem allow us to e.g. skip all blobs with nodes and only download a subset of the data we're actually interested in?

I understand that some of these use cases are maybe better handled e.g. with an Overpass Turbo query but I still wanted to raise the question here and open up the conversation as food for thought.

**Comment by joto** [comment]
Osmium already supports reading from a URL if you have the `curl` binary installed. Just use a URL instead of a file name. No range-based requests are used, because osmium always reads file from start to finish, on disk or on the net doesn't matter here, because osmium is all about stream-based processing.

The stream-based processing versus some clever accessing of only parts of the data by reading only some blocks in the PBF comes up occasionally. But this would mean a huge rearchitecting of osmium and would mean we loose support for XML and other file formats, so this is unlikely to happen. Also blocks in PBF files are usually not layed out in a way that it would make sense to only read some of them. They could be, but in practice they are not. And it is unclear exactly what this would be used for and how much it would help etc. For other implementations with different goals look at the Protomaps stuff and at the PBF file reading in Tilemaker which reads the data in parallel using the PBF block structure.

**Comment by daniel-j-h** [comment]
Got it, that sounds reasonable.

So in summary: while in theory there might be some optimizations with random or byte-range based access, in practice neither the .osm.pbf files out there nor the libosmium code base were designed for this use case.

How .osm.pbf files and libosmiunm are meant to be used it in (multiple) linear scans over the file.

Thank you this clarifies things, closing here! :raised_hands:
