### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by joto** [osmcode/libosmium#4]
The exception handling in Osmium is a bit of a mess. In some parts the usual exceptions (such as std::runtime_error) are used, some parts use special Osmium exceptions. This has to be straightened out. We have to look at all cases from the perspective of the library user and decide what the best kind of exception is in each case and what extra data is needed in the exception.

Everything that can't throw an exception should get a "noexcept".

**Comment by daniel-j-h** [comment]
> All functions throwing exceptions need to document which exceptions they throw

Strictly speaking, it would be great to also document exception safety and guarantees we can give and also what we can not guarantee for. For example, where can we provide the strong exception safety guarantee, where is it not possible (or simply not implemented) and what happens in those cases.

[This](http://stackoverflow.com/a/1853769) gives a great summary of what this means for the code.


The documentation currently lacks this, making it hard to reason about correctness for simple scenarios like: "what happens if my handler throws", and "what happens if my handler throws and there is a node cache handler in front of it" and "how is the interaction between handlers when one of them throws?" and more. Of course I can read the code and do some tests, but it would be great to document this.

**Comment by joto** [comment]
I agree. But it is a huge task and we have to keep the documentation in sync with the implementation. So more of a long-term project. :-)

**Comment by joto** [comment]
This has mostly been done now. If anybody finds cases where exceptions are not used in the right way, open individual issues for it.
