### ISSUE TITLE
Investigate differences cmake "NMake Makefiles" vs "Visual Studio 14 Win64"

### ISSUE THREAD

**Issue by BergWerkGIS** [osmcode/libosmium#71]
### `cmake -G "Visual Studio 14 Win64"` and `msbuild`

* build is successful (`-DCMAKE_BUILD_TYPE=Dev` and `Release`)
* `#pragma`s are honored #69 #68 
* `ctest -C Release -V -E testdata-multipolygon` obviously fails, because there are only VS project files: __Figure out, how to run tests with VS.__
* output is not nice to look at
* see https://ci.appveyor.com/project/BergWerkGIS/libosmium/build/1.0.29

### `NMake Makefiles 14 Win64"` and `nmake`
* build is partially successful (`-DCMAKE_BUILD_TYPE=Dev` fails, `Release` is successfull)
* `#pragma`s are _not_ honored #69 #68 
* tests run
* output is nice to look at, with `%` progress

@joto How do you want to proceed?
VS-way or NMake-way?

**Comment by joto** [comment]
Ok, first question is: Why are there all these differences? Don't these tools call the compiler with the same options in the end? Maybe I don't understand how they work.

The next question is: What will the typical user use? We want to have a system that is close to what a real developer would use and that we can recommend to developers to use. If we have something that works fine, but nobody would use the same setup, how can we be confident that we are not breaking the users experience?

**Comment by BergWerkGIS** [comment]
> Why are there all these differences?

Well, I would say different types of project files support different functionality and cmake might not be able to translate every requirement into every project type.

> What will the typical user use?

Hard to say.
I've been a Visual Studio user since came out, so I would opt for that.
But there might be different use cases, especially in the Open Source space.

Although that might change a bit with the free Community Edition:
http://www.visualstudio.com/en-us/downloads/download-visual-studio-vs.aspx
http://www.visualstudio.com/en-us/products/free-developer-offers-vs.aspx
http://www.visualstudio.com/en-us/news/vs2013-community-vs.aspx

**Comment by alex85k** [comment]
On VS2013 with msbuild I had run tests with simple
```
set PATH=%PATH%;%PREFIX%/bin
if "%TESTS%"=="ON" ctest -VV >..\..\%~n0_tests.log
```
Maybe testdata-multipolygon just does not see ```spatialite.exe``` in PATH or it is not working?

I had also repeating problems before until I managed to build GDAL+OGR with spatialite module
(had to patch nmake.opt to catch spatialite instead of sqlite):
https://github.com/alex85k/winbuilds/blob/master/build_gdal.bat#L33

Maybe something like that fragment is needed in https://github.com/BergWerkGIS/mapnik-dependencies/blob/windows/patches/gdal.diff ?
(however, it will requre freexl, readosm and spatialite to build, maybe my other batch file fragments can be useful, fixed for VS2015 if needed)

**Comment by joto** [comment]
We are going the `msbuild` route. The tests and everything else work now.
