### ISSUE TITLE
Appveyor timeout

### ISSUE THREAD

**Issue by joto** [osmcode/libosmium#80]
For the `Dev` build we are running into the 30 minutes Appveyor timeout. It seems some people have successfully asked for longer timeouts, but even if thats longer, it is a rather long time to wait for a build...

/cc @springmeyer @BergWerkGIS

**Comment by springmeyer** [comment]
I think one good short term approach would be to split the build using a matrix that allows just a few tests to build/run for each job.

Also builds will be a lot faster when we can avoid needing to set a custom `os` (https://github.com/osmcode/libosmium/blob/master/appveyor.yml#L19). This is because if we don't set an `os` the builds run on better hardware. However last I checked the default OS did not have visual studio 2015 on it yet and you need a custom os (http://www.appveyor.com/blog/2015/01/20/visual-studio-2015-ctp-image).

**Comment by BergWerkGIS** [comment]
I'm also on the AppVeyor free plan, but builds ran for 35 minutes without being stopped:
https://ci.appveyor.com/project/BergWerkGIS/libosmium/build/1.0.34

**Comment by BergWerkGIS** [comment]
Very interesting. I seem to have a 40 minute limit.
Enough for `Release` but not enough for `Dev`:

https://ci.appveyor.com/project/BergWerkGIS/libosmium/build/1.0.35/job/236ybmobysgoliic/messages

**Comment by joto** [comment]
I have seen people mention a 30 min limit and others a 40 min limit. Here is the message from the `libosmium` repos: https://ci.appveyor.com/project/Mapbox/libosmium/build/1.0.70/job/y63ypruwsmox1jbp/messages

**Comment by joto** [comment]
For the time being we'll disable HEADER builds which means we stay under the timeout limit. We'll revisit this issue when there are changes at Appveyor.
