### ISSUE TITLE
Failing index/test_typed_mmap

### ISSUE THREAD

**Issue by joto** [osmcode/libosmium#81]
The test fails on Windows but doesn't give any output, maybe it just crashes. @BergWerkGIS: can you investigate? Maybe commenting out test cases and trying each one separately, so that we can see which one is the problem? You can also try calling the test exe without ctest. Just calling it directly should work.

**Comment by BergWerkGIS** [comment]
Does this help?

![image](https://cloud.githubusercontent.com/assets/4549888/6151130/1aa487b2-b214-11e4-84a7-666006cb5c08.png)

**Comment by joto** [comment]
I managed to fix one of the checks, but not the other. Problem was (I think) that you can't delete the file on Windows while it is open, on Linux that is okay. But I can't figure out what the problem is in the second case.

**Comment by BergWerkGIS** [comment]
No, you cannot delete a file that a process still has an open handle to.

**Comment by BergWerkGIS** [comment]
That one is strange.
My problem: because of how the `catch.hpp` test runner starts the tests, I cannot debug, neither with Visual Studio directly on the source, nor with with WinDbg on the `exe`.
Using `RelWithDebInfo`.

If I comment out
https://github.com/osmcode/libosmium/blob/master/test/t/index/test_typed_mmap.cpp#L82-L93
`unlink` works, otherwise not.

Any change, that there are resources, that are not freed?
Interestingly `0 == close` doesn't have a problem, whereas `0 == unlink` does.

No idea what the problem is.

**Comment by joto** [comment]
Maybe it has something to do with https://github.com/osmcode/libosmium/blob/master/include/mmap_for_windows.hpp#L100 ?

Can you try checking `errno` after the `unlink`. Maybe it tells us something?

**Comment by joto** [comment]
The reason was the dangling handle. Fixed now after the reorganization of the code.
