### ISSUE TITLE
Missing dependency in build instructions?

### ISSUE THREAD

**Issue by bladeSk** [osmcode/libosmium#89]
It seems `google/sparsetable` doesn't get installed with the `libprotobuf-dev` package. I got the library working by installing `apt-get install sparsehash`.

**Comment by joto** [comment]
I assume you are talking about the `libprotobuf-dev` package from Debian/Ubuntu. That package contains the ["old osmium"](https://github.com/joto/osmium), not the "new package" this repository is about.

Second, yes, that package doesn't depend on `sparsehash` because many parts of it can be used without it.

And third, Debian/Ubuntu package problems should usually be reported through the mechanism of those distros to get to the right people. (In this case I am maintaining both old and new libosmium and sort of involved in the Debian packaging, so it doesn't matter much.)
