### ISSUE TITLE
Memory Bug: [terminate called after throwing an instance of 'std::bad_alloc']

### ISSUE THREAD

**Issue by abdultz** [osmcode/libosmium#93]
`./osmium_serdump /home/user/Downloads/2012/planet-120912.osm.bz2 /home/user/Downloads/2012/ser/`

Output:
```terminate called after throwing an instance of 'std::bad_alloc'```
   ``` what():  std::bad_alloc```
   ``` Aborted (core dumped)```

The program terminates even after I ran it on machines having >40GB of RAM
The last execution ran for > 4 hours and `System Monitor (Linux)` reported about > 16GB of Memory being used by the process. The output file size reached to 67.3GB while the input `planet-120912.osm.bz2` is of size `24.5GB`
Is it possible to put the library/program in verbose/debug mode???

The old library https://github.com/minad/osm2shp appears to be working on the same input file without consuming much memory but then it is not supporting recent file formats such as OPL

Another run terminated at 69.4GB output
This time I ran the process in Debug mode within Netbeans (See attached Screenshot...
![screenshot from 2015-05-29 193757](https://cloud.githubusercontent.com/assets/12512518/7884317/78692180-063a-11e5-9d40-2476f62f4ddd.png)
)

**Comment by joto** [comment]
Please read the comments at the beginning of the `osmium_serdump.cpp` file. You have to change the source code for large input files.

Unfortunately there isn't much documentation yet about how to do all this. There is a beginning here:
http://osmcode.org/libosmium/manual/libosmium-manual.html#indexes . If you tell us what you are trying to do, maybe we can help some more?

**Comment by abdultz** [comment]
I changed the line 
`typedef osmium::index::map::SparseMemArray<osmium::unsigned_object_id_type, size_t> offset_index_type;`
to 
`typedef osmium::index::map::DenseMmapArray<osmium::unsigned_object_id_type, size_t> offset_index_type;`
for large (planet) files

It was giving an error
`/home/user/Desktop/libosmium-master/examples/osmium_serdump.cpp:45:29: error: ‘DenseMmapArray’ in namespace ‘osmium::index::map’ does not name a template type
`typedef osmium::index::map::DenseMmapArray<osmium::unsigned_object_id_type, size_t> offset_index_type;`

You have to include the missing header:
`#include <osmium/index/map/dense_mmap_array.hpp>`

Compilation was successful... fingers crossed for the output!!!

**Comment by abdultz** [comment]
Same error again with `DenseMmap` but this time the output `data.osm.ser` doubled in size ~112GB
and the process was able to consume `~20GB of memory (RAM) before termination`

I think you should run/debug it on a `planet file`

I also have use of another program `export_to_wkt.cpp`
https://github.com/osmcode/osmium-contrib
and as it is referring to the same `library` and `headers` I assume it will crash too...
Also, it is missing the same header (used for large files)
` #include <osmium/index/map/dense_mmap_array.hpp>`
You might also want to include that header in the example.

How about conditional `typedefs`???
You can check the file size before declaring the `typedef`s and select the appropriate one at run-time!

N.B.: I am still going through C++11

**Comment by joto** [comment]
These programs do work for planet sized data. But they need a lot of memory, that is normal. With a lot I mean 10s of GBs. But depending on what you want, different strategies can be used for larger data sizes than for smaller ones. These are, unfortunately, examples that are not well documented and not something which can be used out of the box. I am sorry this is all a bit vague. But if I had the time I would have documented those examples better and described what there limitations are. As things currently stand they work for smaller data sizes out of the box, because I thought that is what people will test them with. But if you want to work with larger data size, you have to know more about how Osmium works internally to get this to work.

You can't have conditional typedefs at runtime. But there is a different mechanism for that. This is used in `osmium_toogr.cpp` for instance. You can decide on the command line which type of index to use.

Again, if you tell us, what you are trying to do, I could probably help you some more.
